const {published}=require('./store');

function e(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt(iso){try{return new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(iso));}catch{return iso||'';}}
function shell(title,body,desc='نبض ساردو؛ رسانه محلی ساردوئیه و جنوب کرمان'){
return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(desc)}"><meta name="theme-color" content="#090b0f"><link rel="stylesheet" href="/assets/site.css"></head><body>${body}<script src="/assets/site.js" defer></script></body></html>`;}
function logo(){return `<a class="brand" href="/"><span class="logo">ن<span></span></span><b>نبض ساردو<small>NABEZ SARDO · NEWSROOM</small></b></a>`;}
function header(db){return `<div class="top"><div class="wrap row"><span>نبض ساردو · رسانه محلی ساردوئیه و جنوب کرمان</span><span>${e(db.settings.tagline)}</span></div></div><header><div class="wrap row main">${logo()}<div class="actions"><a class="btn ghost" href="/all-news">آرشیو</a><a class="btn primary" href="/send-news">ارسال خبر مردمی</a></div></div></header><nav><div class="wrap navrow"><a href="/">صفحه اصلی</a><a href="/all-news">آخرین اخبار</a>${db.categories.slice(0,7).map(c=>`<a href="/category/${encodeURIComponent(c.id)}">${e(c.name)}</a>`).join('')}<a href="/contact">تماس</a></div></nav>`;}
function footer(){return `<footer><div class="wrap foot"><div><h3>نبض ساردو</h3><p>خبر دقیق، روایت انسانی و هویت منطقه.</p></div><div><h4>رسانه</h4><a href="/about">درباره ما</a><a href="/contact">تماس</a><a href="/send-news">ارسال خبر</a></div><div><h4>دسترسی</h4><a href="/">خانه</a><a href="/all-news">آرشیو</a></div><div><h4>NABEZ SARDO</h4><p>Independent Local Newsroom</p></div></div><div class="copy">© نبض ساردو — تمامی حقوق محفوظ است.</div></footer>`;}
function card(a,db){const c=db.categories.find(x=>x.id===a.categoryId);return `<article class="card tilt"><a href="/news/${encodeURIComponent(a.slug)}"><img src="${e(a.image||'/assets/placeholder.svg')}" alt="${e(a.title)}"></a><div class="pad"><span class="eyebrow">${e(c?.name||'خبر')}</span><h3><a href="/news/${encodeURIComponent(a.slug)}">${e(a.title)}</a></h3><p>${e(a.lead||'')}</p><a class="more" href="/news/${encodeURIComponent(a.slug)}">مطالعه خبر ←</a></div></article>`;}
function home(db){
 const latest=published(db).slice(0,6),featured=published(db).find(a=>a.featured)||latest[0];
 return shell('نبض ساردو | اخبار ساردوئیه و جنوب کرمان',`${header(db)}
 <main><section class="hero"><div class="hero-bg"></div><div class="wrap hero-grid"><div class="hero-copy reveal"><span class="chip">3D EDITORIAL · SARDOUIYEH</span><h1>نبضِ ساردوئیه،<br>با یک هویت رسانه‌ای تازه</h1><p>خبر محلی، گزارش میدانی، روایت تصویری و صدای مردم؛ در یک تجربه خبری مدرن و متفاوت.</p><div class="actions"><a class="btn gold" href="#latest">تازه‌ترین خبرها</a><a class="textlink" href="/about">درباره تحریریه</a></div></div><div class="hero-art reveal"><div class="orbit o1"></div><div class="orbit o2"></div><div class="mark3d tilt">ن<div class="pulse">⌁</div></div></div></div></section>
 <section class="breaking"><div class="wrap row"><b>نبض فوری</b><span>مهم‌ترین رویدادهای ساردوئیه و جنوب کرمان؛ سریع، دقیق و محلی.</span><i>● LIVE DESK</i></div></section>
 <section class="wrap cats">${db.categories.slice(0,7).map(c=>`<a href="/category/${c.id}"><b>✦</b><span>${e(c.name)}</span></a>`).join('')}</section>
 <section id="latest" class="wrap section"><div class="sectionhead"><div><span class="eyebrow">LATEST / NEWSROOM</span><h2>آخرین اخبار</h2></div><a class="more" href="/all-news">آرشیو کامل</a></div>${latest.length?`<div class="grid news">${latest.map(a=>card(a,db)).join('')}</div>`:`<div class="empty"><h3>هنوز خبری منتشر نشده است</h3><p>از پنل تحریریه اولین خبر را منتشر کنید.</p></div>`}</section>
 <section class="focus"><div class="wrap focusgrid"><div><span class="eyebrow">SARDOUIYEH FOCUS</span><h2>ساردوئیه در کانون</h2><p>روایت مسائل واقعی مردم، ظرفیت‌های منطقه، کشاورزی، گردشگری، آموزش، فرهنگ و ورزش.</p><a class="btn ghost" href="/all-news">ورود به آرشیو</a></div><div class="topics">${[['01','شهر و روستا'],['02','کشاورزی'],['03','فرهنگ و ورزش'],['04','گردشگری']].map(x=>`<div class="topic tilt"><small>${x[0]}</small><h3>${x[1]}</h3><p>خبرها و گزارش‌های منتخب این حوزه.</p></div>`).join('')}</div></div></section>
 <section class="wrap citizen"><div><span class="eyebrow">CITIZEN NEWSROOM</span><h2>شما هم خبرنگار نبض ساردو باشید</h2><p>خبر، عکس، ویدئو یا سوژه محلی را برای تحریریه ارسال کنید.</p></div><a class="btn primary" href="/send-news">ارسال خبر</a></section></main>${footer()}`);}
function archive(db,q=''){const all=published(db).filter(a=>!q||a.title.includes(q)||a.lead.includes(q));return shell('آرشیو اخبار | نبض ساردو',`${header(db)}<main class="wrap page"><div class="pagehead"><span class="eyebrow">ARCHIVE</span><h1>آرشیو اخبار</h1></div><form class="search" action="/all-news"><input name="q" value="${e(q)}" placeholder="جستجو در خبرها"><button class="btn primary">جستجو</button></form><div class="grid news">${all.map(a=>card(a,db)).join('')||'<div class="empty">خبری پیدا نشد.</div>'}</div></main>${footer()}`);}
function article(db,a){const c=db.categories.find(x=>x.id===a.categoryId);return shell(a.title+' | نبض ساردو',`${header(db)}<main class="wrap article"><article><span class="eyebrow">${e(c?.name||'خبر')}</span><h1>${e(a.title)}</h1><p class="lead">${e(a.lead||'')}</p><div class="meta"><span>${e(a.author||'تحریریه نبض ساردو')}</span><span>${e(a.location||'ساردوئیه')}</span><span>${fmt(a.publishedAt||a.createdAt)}</span></div>${a.image?`<img class="cover" src="${e(a.image)}" alt="${e(a.title)}">`:''}<div class="body">${e(a.body||'').split('\n').filter(Boolean).map(p=>`<p>${p}</p>`).join('')}</div></article></main>${footer()}`,a.lead||'');}
function category(db,c){const list=published(db).filter(a=>a.categoryId===c.id);return shell(c.name+' | نبض ساردو',`${header(db)}<main class="wrap page"><span class="eyebrow">CATEGORY</span><h1>${e(c.name)}</h1><div class="grid news">${list.map(a=>card(a,db)).join('')||'<div class="empty">هنوز خبری در این دسته منتشر نشده است.</div>'}</div></main>${footer()}`);}
function simple(db,type,ok=false){let title='',content='';if(type==='about'){title='درباره نبض ساردو';content=`<p class="lead">نبض ساردو رسانه‌ای محلی برای پوشش دقیق، سریع و مسئولانه اخبار ساردوئیه و جنوب کرمان است.</p><div class="grid info"><div class="panel"><h3>ماموریت</h3><p>خبر محلی قابل اتکا و روایت مسائل واقعی مردم.</p></div><div class="panel"><h3>اصول تحریریه</h3><p>دقت، راستی‌آزمایی، احترام و استقلال.</p></div><div class="panel"><h3>تمرکز منطقه‌ای</h3><p>ساردوئیه، جیرفت و جنوب کرمان.</p></div></div>`;}else if(type==='contact'){title='تماس با ما';content=`${ok?'<div class="success">پیام شما ثبت شد.</div>':''}<form class="form" method="post"><label>نام<input name="name" required></label><label>راه ارتباطی<input name="contact" required></label><label>موضوع<input name="subject" required></label><label>پیام<textarea name="message" required></textarea></label><button class="btn primary">ارسال پیام</button></form>`;}else{title='ارسال خبر مردمی';content=`${ok?'<div class="success">خبر شما برای تحریریه ثبت شد.</div>':''}<form class="form" method="post"><label>نام<input name="name" required></label><label>شماره تماس<input name="phone" required></label><label>محل رویداد<input name="location" required></label><label>عنوان خبر<input name="headline" required></label><label>شرح خبر<textarea name="details" required></textarea></label><label>لینک عکس یا ویدئو<input name="mediaLink"></label><button class="btn primary">ارسال برای تحریریه</button></form>`;}return shell(title+' | نبض ساردو',`${header(db)}<main class="wrap page"><span class="eyebrow">NABEZ SARDO</span><h1>${title}</h1>${content}</main>${footer()}`);}
function login(error=false){return shell('ورود تحریریه | نبض ساردو',`<main class="login"><div class="loginbox">${logo()}<h1>ورود تحریریه</h1>${error?'<div class="error">اطلاعات ورود نادرست است.</div>':''}<form method="post"><label>نام کاربری<input name="username" required></label><label>رمز عبور<input type="password" name="password" required></label><button class="btn primary">ورود</button></form></div></main>`);}
function admin(db){const a=[...db.articles].sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));return shell('مدیریت | نبض ساردو',`<div class="adminbar">${logo()}<a href="/">مشاهده سایت</a><a href="/admin/logout">خروج</a></div><main class="wrap admin"><div class="sectionhead"><div><span class="eyebrow">NEWSROOM ADMIN</span><h1>داشبورد تحریریه</h1></div><a class="btn primary" href="/admin/articles/new">+ خبر جدید</a></div><div class="stats"><div><b>${a.length}</b><span>کل خبرها</span></div><div><b>${a.filter(x=>x.status==='published').length}</b><span>منتشرشده</span></div><div><b>${db.citizens.length}</b><span>خبر مردمی</span></div><div><b>${db.contacts.length}</b><span>پیام تماس</span></div></div><section class="panel"><h2>خبرها</h2>${a.map(x=>`<div class="adminrow"><div><b>${e(x.title)}</b><small>${x.status==='published'?'منتشرشده':'پیش‌نویس'} · ${fmt(x.createdAt)}</small></div><div><a href="/admin/articles/${x.id}/edit">ویرایش</a><form method="post" action="/admin/articles/${x.id}/delete"><button>حذف</button></form></div></div>`).join('')||'<p>هنوز خبری ثبت نشده است.</p>'}</section><div class="gridadmin"><section class="panel"><h2>خبرهای مردمی</h2>${db.citizens.slice(0,20).map(x=>`<details><summary>${e(x.headline)} — ${e(x.name)}</summary><p>${e(x.details)}</p><small>${e(x.phone)} · ${e(x.location)}</small></details>`).join('')||'<p>موردی نیست.</p>'}</section><section class="panel"><h2>پیام‌ها</h2>${db.contacts.slice(0,20).map(x=>`<details><summary>${e(x.subject)} — ${e(x.name)}</summary><p>${e(x.message)}</p><small>${e(x.contact)}</small></details>`).join('')||'<p>پیامی نیست.</p>'}</section></div></main>`);}
function editor(db,a={},action='/admin/articles/new',title='خبر جدید'){return shell(title+' | نبض ساردو',`<div class="adminbar">${logo()}<a href="/admin">داشبورد</a></div><main class="wrap admin"><h1>${title}</h1><form class="form" method="post" action="${action}"><label>عنوان<input name="title" value="${e(a.title||'')}" required></label><label>اسلاگ<input name="slug" value="${e(a.slug||'')}"></label><label>دسته‌بندی<select name="categoryId">${db.categories.map(c=>`<option value="${c.id}" ${a.categoryId===c.id?'selected':''}>${e(c.name)}</option>`).join('')}</select></label><label>لید<textarea name="lead">${e(a.lead||'')}</textarea></label><label>متن کامل<textarea class="big" name="body">${e(a.body||'')}</textarea></label><div class="twocol"><label>خبرنگار<input name="author" value="${e(a.author||'تحریریه نبض ساردو')}"></label><label>محل<input name="location" value="${e(a.location||'ساردوئیه')}"></label></div><div class="twocol"><label>وضعیت<select name="status"><option value="draft">پیش‌نویس</option><option value="published" ${a.status==='published'?'selected':''}>منتشرشده</option></select></label><label>خبر ویژه<select name="featured"><option value="0">خیر</option><option value="1" ${a.featured?'selected':''}>بله</option></select></label></div><label>URL تصویر<input name="image" value="${e(a.image||'')}"></label><button class="btn primary">ذخیره</button></form></main>`);}
module.exports={home,archive,article,category,simple,login,admin,editor};