function e(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt(iso){try{return new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(iso));}catch{return iso||'';}}
function shell(title,body,desc='نبض ساردو؛ رسانه محلی ساردوئیه و جنوب کرمان'){
return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(desc)}"><meta name="theme-color" content="#090b0f"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&family=Vazirmatn:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/editor.css"></head><body>${body}<script src="/assets/site.js" defer></script><script src="/assets/editor.js" defer></script></body></html>`;}
function logo(){return `<a class="brand" href="/"><span class="logo">ن<span></span></span><b>نبض ساردو<small>NABEZ SARDO · NEWSROOM</small></b></a>`;}
function header(db){return `<div class="top"><div class="wrap row"><span>نبض ساردو · رسانه محلی ساردوئیه و جنوب کرمان</span><span>${e(db.settings.tagline)}</span></div></div><header><div class="wrap row main">${logo()}<div class="actions"><a class="btn ghost" href="/all-news">آرشیو</a><a class="btn primary" href="/send-news">ارسال خبر مردمی</a></div></div></header><nav><div class="wrap navrow"><a href="/">صفحه اصلی</a><a href="/all-news">آخرین اخبار</a>${db.categories.slice(0,7).map(c=>`<a href="/category/${encodeURIComponent(c.id)}">${e(c.name)}</a>`).join('')}<a href="/contact">تماس</a></div></nav>`;}
function footer(){return `<footer><div class="wrap foot"><div><h3>نبض ساردو</h3><p>خبر دقیق، روایت انسانی و هویت منطقه.</p></div><div><h4>رسانه</h4><a href="/about">درباره ما</a><a href="/contact">تماس</a><a href="/send-news">ارسال خبر</a></div><div><h4>دسترسی</h4><a href="/">خانه</a><a href="/all-news">آرشیو</a></div><div><h4>NABEZ SARDO</h4><p>Independent Local Newsroom</p></div></div><div class="copy">© نبض ساردو — تمامی حقوق محفوظ است.</div></footer>`;}
function imageRatio(a){const r=Number(a?.imageRatio);return Number.isFinite(r)&&r>0?r:16/9;}
function imageOrientation(a){const o=String(a?.imageOrientation||'');if(['portrait','square','landscape'].includes(o))return o;const r=imageRatio(a);return r<.92?'portrait':r>1.08?'landscape':'square';}
function card(a,db){const c=db.categories.find(x=>x.id===a.categoryId),ratio=imageRatio(a),orient=imageOrientation(a);return `<article class="card tilt"><a class="card-media ${orient}" style="--image-ratio:${ratio}" href="/news/${encodeURIComponent(a.slug)}"><img src="${e(a.image||'/assets/placeholder.svg')}" alt="${e(a.title)}"></a><div class="pad"><span class="eyebrow">${e(c?.name||'خبر')}</span><h3><a href="/news/${encodeURIComponent(a.slug)}">${e(a.title)}</a></h3><p>${e(a.lead||'')}</p><a class="more" href="/news/${encodeURIComponent(a.slug)}">مطالعه خبر ←</a></div></article>`;}

function oldBody(a){return e(a.body||'').split('\n').filter(Boolean).map(p=>`<p>${p}</p>`).join('');}
module.exports={e,fmt,shell,logo,header,footer,card,oldBody,imageRatio,imageOrientation};