const {published}=require('./store');
const {e,shell,header,footer,card,oldBody}=require('./view-common');

function home(db){
 const latest=published(db).slice(0,6);
 return shell('نبض ساردو | اخبار ساردوئیه و جنوب کرمان',`${header(db)}
 <main><section class="hero"><div class="hero-bg"></div><div class="wrap hero-grid"><div class="hero-copy reveal"><span class="chip">3D EDITORIAL · SARDOUIYEH</span><h1>نبضِ ساردوئیه،<br>با یک هویت رسانه‌ای تازه</h1><p>خبر محلی، گزارش میدانی، روایت تصویری و صدای مردم؛ در یک تجربه خبری مدرن و متفاوت.</p><div class="actions"><a class="btn gold" href="#latest">تازه‌ترین خبرها</a><a class="textlink" href="/about">درباره تحریریه</a></div></div><div class="hero-art reveal"><div class="orbit o1"></div><div class="orbit o2"></div><div class="mark3d tilt">ن<div class="pulse">⌁</div></div></div></div></section>
 <section class="breaking"><div class="wrap row"><b>نبض فوری</b><span>مهم‌ترین رویدادهای ساردوئیه و جنوب کرمان؛ سریع، دقیق و محلی.</span><i>● LIVE DESK</i></div></section>
 <section class="wrap cats">${db.categories.slice(0,7).map(c=>`<a href="/category/${c.id}"><b>✦</b><span>${e(c.name)}</span></a>`).join('')}</section>
 <section id="latest" class="wrap section"><div class="sectionhead"><div><span class="eyebrow">LATEST / NEWSROOM</span><h2>آخرین اخبار</h2></div><a class="more" href="/all-news">آرشیو کامل</a></div>${latest.length?`<div class="grid news">${latest.map(a=>card(a,db)).join('')}</div>`:`<div class="empty"><h3>هنوز خبری منتشر نشده است</h3><p>از پنل تحریریه اولین خبر را منتشر کنید.</p></div>`}</section>
 <section class="focus"><div class="wrap focusgrid"><div><span class="eyebrow">SARDOUIYEH FOCUS</span><h2>ساردوئیه در کانون</h2><p>روایت مسائل واقعی مردم، ظرفیت‌های منطقه، کشاورزی، گردشگری، آموزش، فرهنگ و ورزش.</p><a class="btn ghost" href="/all-news">ورود به آرشیو</a></div><div class="topics">${[['01','شهر و روستا'],['02','کشاورزی'],['03','فرهنگ و ورزش'],['04','گردشگری']].map(x=>`<div class="topic tilt"><small>${x[0]}</small><h3>${x[1]}</h3><p>خبرها و گزارش‌های منتخب این حوزه.</p></div>`).join('')}</div></div></section>
 <section class="wrap citizen"><div><span class="eyebrow">CITIZEN NEWSROOM</span><h2>شما هم خبرنگار نبض ساردو باشید</h2><p>خبر، عکس، ویدئو یا سوژه محلی را برای تحریریه ارسال کنید.</p></div><a class="btn primary" href="/send-news">ارسال خبر</a></section></main>${footer()}`);}
function archive(db,q=''){const all=published(db).filter(a=>!q||a.title.includes(q)||a.lead.includes(q));return shell('آرشیو اخبار | نبض ساردو',`${header(db)}<main class="wrap page"><div class="pagehead"><span class="eyebrow">ARCHIVE</span><h1>آرشیو اخبار</h1></div><form class="search" action="/all-news"><input name="q" value="${e(q)}" placeholder="جستجو در خبرها"><button class="btn primary">جستجو</button></form><div class="grid news">${all.map(a=>card(a,db)).join('')||'<div class="empty">خبری پیدا نشد.</div>'}</div></main>${footer()}`);}
function article(db,a){const c=db.categories.find(x=>x.id===a.categoryId);const body=a.bodyHtml||oldBody(a);const gallery=Array.isArray(a.gallery)?a.gallery:[];return shell(a.title+' | نبض ساردو',`${header(db)}<main class="wrap article"><article><span class="eyebrow">${e(c?.name||'خبر')}</span><h1>${e(a.title)}</h1><p class="lead">${e(a.lead||'')}</p><div class="meta"><span>${e(a.author||'تحریریه نبض ساردو')}</span><span>${e(a.location||'ساردوئیه')}</span><span>${new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(a.publishedAt||a.createdAt))}</span></div>${a.image?`<div class="cover-frame"><img class="cover" src="${e(a.image)}" alt="${e(a.title)}"></div>`:''}<div class="body rich-content">${body}</div>${gallery.length?`<section class="article-gallery"><h3>گالری تصاویر</h3><div class="article-gallery-grid">${gallery.map((url,i)=>`<img src="${e(url)}" alt="${e(a.title)} - تصویر ${i+1}">`).join('')}</div></section>`:''}</article></main>${footer()}`,a.lead||'');}
function category(db,c){const list=published(db).filter(a=>a.categoryId===c.id);return shell(c.name+' | نبض ساردو',`${header(db)}<main class="wrap page"><span class="eyebrow">CATEGORY</span><h1>${e(c.name)}</h1><div class="grid news">${list.map(a=>card(a,db)).join('')||'<div class="empty">هنوز خبری در این دسته منتشر نشده است.</div>'}</div></main>${footer()}`);}
function simple(db,type,ok=false){let title='',content='';if(type==='about'){title='درباره نبض ساردو';content=`<p class="lead">نبض ساردو رسانه‌ای محلی برای پوشش دقیق، سریع و مسئولانه اخبار ساردوئیه و جنوب کرمان است.</p><div class="grid info"><div class="panel"><h3>ماموریت</h3><p>خبر محلی قابل اتکا و روایت مسائل واقعی مردم.</p></div><div class="panel"><h3>اصول تحریریه</h3><p>دقت، راستی‌آزمایی، احترام و استقلال.</p></div><div class="panel"><h3>تمرکز منطقه‌ای</h3><p>ساردوئیه، جیرفت و جنوب کرمان.</p></div></div>`;}else if(type==='contact'){title='تماس با ما';content=`${ok?'<div class="success">پیام شما ثبت شد.</div>':''}<form class="form" method="post"><label>نام<input name="name" required></label><label>راه ارتباطی<input name="contact" required></label><label>موضوع<input name="subject" required></label><label>پیام<textarea name="message" required></textarea></label><button class="btn primary">ارسال پیام</button></form>`;}else{title='ارسال خبر مردمی';content=`${ok?'<div class="success">خبر شما برای تحریریه ثبت شد.</div>':''}<form class="form" method="post"><label>نام<input name="name" required></label><label>شماره تماس<input name="phone" required></label><label>محل رویداد<input name="location" required></label><label>عنوان خبر<input name="headline" required></label><label>شرح خبر<textarea name="details" required></textarea></label><label>لینک عکس یا ویدئو<input name="mediaLink"></label><button class="btn primary">ارسال برای تحریریه</button></form>`;}return shell(title+' | نبض ساردو',`${header(db)}<main class="wrap page"><span class="eyebrow">NABEZ SARDO</span><h1>${title}</h1>${content}</main>${footer()}`);}
module.exports={home,archive,article,category,simple};