const {published}=require('./store');
const {e,shell,header,footer,card,oldBody,imageRatio,imageOrientation,absoluteUrl,PUBLIC_BASE,catEn}=require('./view-common');

function compactText(v='',max=160){
  const s=String(v||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
  return s.length>max?s.slice(0,max-1).trim()+'…':s;
}
function siteSchema(){
  return [
    {'@context':'https://schema.org','@type':'WebSite',name:'نبض ساردو',alternateName:'Nabez Sardo',url:PUBLIC_BASE+'/',inLanguage:'fa-IR',potentialAction:{'@type':'SearchAction',target:absoluteUrl('/search?q={search_term_string}'),'query-input':'required name=search_term_string'}},
    {'@context':'https://schema.org','@type':'NewsMediaOrganization',name:'نبض ساردو',alternateName:'Nabez Sardo',url:PUBLIC_BASE+'/',description:'رسانه محلی ساردوئیه، جیرفت و جنوب کرمان',areaServed:[{'@type':'Place',name:'ساردوئیه'},{'@type':'Place',name:'جیرفت'},{'@type':'Place',name:'جنوب کرمان'}]}
  ];
}
function articleSchema(a,c){
  const url=absoluteUrl('/news/'+encodeURIComponent(a.slug));
  const authorName=a.author||'تحریریه نبض ساردو';
  const authorType=authorName.includes('تحریریه')?'Organization':'Person';
  const news={'@context':'https://schema.org','@type':'NewsArticle',mainEntityOfPage:{'@type':'WebPage','@id':url},headline:a.title,description:compactText(a.lead||a.body||a.title,220),datePublished:a.publishedAt||a.createdAt,dateModified:a.updatedAt||a.publishedAt||a.createdAt,inLanguage:'fa-IR',isAccessibleForFree:true,articleSection:c?.name||'خبر',keywords:[c?.name,a.location,'ساردوئیه','جیرفت','جنوب کرمان'].filter(Boolean).join(', '),author:{'@type':authorType,name:authorName},publisher:{'@type':'NewsMediaOrganization',name:'نبض ساردو',url:PUBLIC_BASE+'/'},url};
  if(a.image)news.image=[absoluteUrl(a.image)];
  const crumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'صفحه اصلی',item:PUBLIC_BASE+'/'},{'@type':'ListItem',position:2,name:c?.name||'خبر',item:absoluteUrl('/category/'+encodeURIComponent(a.categoryId||''))},{'@type':'ListItem',position:3,name:a.title,item:url}]};
  return [news,crumb];
}

function home(db){
 const latest=published(db).slice(0,6);
 return shell('اخبار ساردوئیه، جیرفت و جنوب کرمان | نبض ساردو',`${header(db)}
 <main><section class="hero"><img class="hero-bg-image" src="/assets/hero-mosque-v2.jpg?v=hero20260920c" alt="" fetchpriority="high" aria-hidden="true"><div class="wrap hero-grid"><div class="hero-copy reveal"><span class="chip">3D EDITORIAL · SARDOUIYEH</span><h1>نبضِ ساردوئیه،<br>با یک هویت رسانه‌ای تازه</h1><p>خبر محلی، گزارش میدانی، روایت تصویری و صدای مردم؛ در یک تجربه خبری مدرن و متفاوت.</p><div class="actions"><a class="btn gold" href="#latest">تازه‌ترین خبرها</a><a class="textlink" href="/about">درباره تحریریه</a></div></div><div class="hero-art reveal"><div class="pulse-stage" aria-hidden="true"><span class="pulse-halo pulse-halo-a"></span><span class="pulse-halo pulse-halo-b"></span><svg class="lux-pulse" viewBox="0 0 520 260" focusable="false"><defs><linearGradient id="pulseGold" x1="24" y1="80" x2="494" y2="178" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#8d6328"/><stop offset=".18" stop-color="#f5d995"/><stop offset=".5" stop-color="#fff1c2"/><stop offset=".78" stop-color="#d7a956"/><stop offset="1" stop-color="#75501e"/></linearGradient><filter id="pulseSoft" x="-30%" y="-80%" width="160%" height="260%"><feGaussianBlur stdDeviation="9"/></filter><filter id="pulseShine" x="-30%" y="-80%" width="160%" height="260%"><feGaussianBlur stdDeviation="2.3"/></filter></defs><path class="pulse-shadow" d="M24 146H138L166 114L198 185L239 63L281 191L320 119L352 146H496" fill="none" stroke="#d7a956" stroke-width="15" stroke-linecap="round" stroke-linejoin="round" filter="url(#pulseSoft)"/><path class="pulse-main" d="M24 146H138L166 114L198 185L239 63L281 191L320 119L352 146H496" fill="none" stroke="url(#pulseGold)" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/><path class="pulse-highlight" d="M24 144H138L166 112L198 183L239 61L281 189L320 117L352 144H496" fill="none" stroke="#fff7db" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" filter="url(#pulseShine)"/><circle class="pulse-node" cx="239" cy="63" r="7" fill="#fff0bd"/></svg><div class="pulse-caption"><span>LIVE / SARDOUIYEH</span><b>نبض خبرهای منطقه</b></div></div></div></div></div></section>
 <section class="breaking"><div class="wrap row"><b>نبض فوری</b><span>مهم‌ترین رویدادهای ساردوئیه و جنوب کرمان؛ سریع، دقیق و محلی.</span><i>● LIVE DESK</i></div></section>
 <section class="wrap cats">${db.categories.slice(0,7).map(c=>`<a href="/category/${c.id}"><b>✦</b><span>${e(c.name)}</span></a>`).join('')}</section>
 <section id="latest" class="wrap section"><div class="sectionhead"><div><span class="eyebrow">LATEST / NEWSROOM</span><h2>آخرین اخبار</h2></div><a class="more" href="/all-news">آرشیو کامل</a></div>${latest.length?`<div class="grid news">${latest.map(a=>card(a,db)).join('')}</div>`:`<div class="empty"><h3>هنوز خبری منتشر نشده است</h3><p>از پنل تحریریه اولین خبر را منتشر کنید.</p></div>`}</section>
 <section class="focus"><div class="wrap focusgrid"><div><span class="eyebrow">SARDOUIYEH FOCUS</span><h2>ساردوئیه در کانون</h2><p>روایت مسائل واقعی مردم، ظرفیت‌های منطقه، کشاورزی، گردشگری، آموزش، فرهنگ و ورزش.</p><a class="btn ghost" href="/all-news">ورود به آرشیو</a></div><div class="topics">${[['01','سیاسی'],['02','کشاورزی'],['03','فرهنگ و ورزش'],['04','گردشگری']].map(x=>`<div class="topic tilt"><small>${x[0]}</small><h3>${x[1]}</h3><p>خبرها و گزارش‌های منتخب این حوزه.</p></div>`).join('')}</div></div></section>
 <section class="wrap citizen"><div class="citizen-copy"><span class="eyebrow">CITIZEN NEWSROOM</span><h2>شما هم خبرنگار نبض ساردو باشید</h2><p>خبر، عکس، ویدئو یا سوژه محلی را برای تحریریه ارسال کنید.</p></div><a class="btn primary" href="/send-news">ارسال خبر</a></section></main>${footer()}`, 'نبض ساردو؛ تازه‌ترین اخبار ساردوئیه، جیرفت و جنوب کرمان',{canonical:'/',schema:siteSchema()});}
function archive(db,q=''){const all=published(db).filter(a=>!q||a.title.includes(q)||a.lead.includes(q));return shell('آخرین اخبار ساردوئیه و جنوب کرمان | نبض ساردو',`${header(db)}<main class="wrap page"><div class="pagehead"><span class="eyebrow">ARCHIVE</span><h1>آرشیو اخبار</h1></div><form class="search" action="/all-news"><input name="q" value="${e(q)}" placeholder="جستجو در خبرها"><button class="btn primary">جستجو</button></form><div class="grid news">${all.map(a=>card(a,db)).join('')||'<div class="empty">خبری پیدا نشد.</div>'}</div></main>${footer()}`,'آرشیو کامل اخبار نبض ساردو',{canonical:'/all-news'});}
function article(db,a){
  const c=db.categories.find(x=>x.id===a.categoryId);
  const body=a.bodyHtml||oldBody(a);
  const bodyEn=a.bodyEn?String(a.bodyEn).split('\n').filter(Boolean).map(p=>`<p>${e(p)}</p>`).join(''):body;
  const gallery=Array.isArray(a.gallery)?a.gallery:[];
  const pub=published(db);
  const same=pub.filter(x=>x.id!==a.id&&x.categoryId===a.categoryId);
  const fallback=pub.filter(x=>x.id!==a.id&&x.categoryId!==a.categoryId);
  const related=[...same,...fallback].slice(0,3);
  const catUrl='/category/'+encodeURIComponent(a.categoryId||'');
  const desc=compactText(a.lead||a.body||a.title,160);
  return shell(a.title+' | نبض ساردو',`${header(db)}<main class="wrap article"><nav class="breadcrumbs" aria-label="مسیر صفحه"><a href="/">خانه</a><span>›</span><a href="${catUrl}"><span class="lang-fa">${e(c?.name||'خبر')}</span><span class="lang-en">${e(catEn(c?.name||'News'))}</span></a></nav><article><span class="eyebrow"><span class="lang-fa">${e(c?.name||'خبر')}</span><span class="lang-en">${e(catEn(c?.name||'News'))}</span></span><h1><span class="lang-fa">${e(a.title)}</span><span class="lang-en">${e(a.titleEn||a.title)}</span></h1><p class="lead"><span class="lang-fa">${e(a.lead||'')}</span><span class="lang-en">${e(a.leadEn||a.lead||'')}</span></p><div class="meta"><span>${e(a.author||'تحریریه نبض ساردو')}</span><span>${e(a.location||'ساردوئیه')}</span><time class="news-date" data-news-date="${e(a.publishedAt||a.createdAt||'')}"></time><span class="article-views">◉ ${Number(a.views||0).toLocaleString('fa-IR')} <span class="lang-fa">بازدید</span><span class="lang-en">views</span></span></div>${a.image?`<div class="cover-frame ${imageOrientation(a)}" data-adaptive-media style="--image-ratio:${imageRatio(a)}"><img class="cover" src="${e(a.image)}" alt="${e(a.title)}"></div>`:''}<div class="body rich-content"><div class="lang-fa">${body}</div><div class="lang-en">${bodyEn}</div></div>${gallery.length?`<section class="article-gallery"><h3>گالری تصاویر</h3><div class="article-gallery-grid">${gallery.map((url,i)=>`<img src="${e(url)}" alt="${e(a.title)} - تصویر ${i+1}">`).join('')}</div></section>`:''}</article>${related.length?`<section class="related-news"><div class="sectionhead"><div><span class="eyebrow">RELATED</span><h2>خبرهای مرتبط</h2></div><a class="more" href="${catUrl}">همه خبرهای این بخش</a></div><div class="grid news">${related.map(x=>card(x,db)).join('')}</div></section>`:''}</main>${footer()}`,desc,{canonical:'/news/'+encodeURIComponent(a.slug),image:a.image||'',ogType:'article',schema:articleSchema(a,c)});
}

function normalizeSearch(v=''){
  return String(v).toLowerCase()
    .replace(/[يى]/g,'ی').replace(/ك/g,'ک')
    .replace(/[ًٌٍَُِّْـ]/g,' ')
    .replace(/\s+/g,' ').trim();
}
function search(db,q=''){
  const query=normalizeSearch(q);
  const all=published(db);
  const list=!query?[]:all.filter(a=>{
    const category=db.categories.find(x=>x.id===a.categoryId)?.name||'';
    const hay=normalizeSearch([a.title,a.lead,a.body,a.author,a.location,category].filter(Boolean).join(' '));
    return query.split(' ').every(part=>hay.includes(part));
  });
  return shell((q?'جستجو: '+q:'جستجو')+' | نبض ساردو',`${header(db)}<main class="wrap page search-page"><div class="pagehead"><span class="eyebrow">SEARCH / NABEZ SARDO</span><h1>جستجو در اخبار</h1><p>${q?`نتایج برای «${e(q)}» — ${list.length.toLocaleString('fa-IR')} خبر`:'عبارت موردنظر را وارد کنید.'}</p></div><form class="search search-large" action="/search" method="get"><input name="q" type="search" value="${e(q)}" placeholder="عنوان، متن، خبرنگار، محل یا موضوع..." autofocus><button class="btn primary">جستجو</button></form>${q?`<div class="grid news">${list.map(a=>card(a,db)).join('')||'<div class="empty">نتیجه‌ای پیدا نشد. عبارت دیگری را امتحان کنید.</div>'}</div>`:''}</main>${footer()}`,'جستجو در آرشیو اخبار نبض ساردو',{canonical:'/search',robots:'noindex,follow'});
}
function category(db,c){const list=published(db).filter(a=>a.categoryId===c.id);return shell('اخبار '+c.name+' | ساردوئیه و جنوب کرمان | نبض ساردو',`${header(db)}<main class="wrap page"><span class="eyebrow">CATEGORY</span><h1>${e(c.name)}</h1><div class="grid news">${list.map(a=>card(a,db)).join('')||'<div class="empty">هنوز خبری در این دسته منتشر نشده است.</div>'}</div></main>${footer()}`,'اخبار '+c.name+' در نبض ساردو',{canonical:'/category/'+encodeURIComponent(c.id)});}
function simple(db,type,ok=false,uploadError=''){let title='',content='';if(type==='about'){title='درباره نبض ساردو';content=`<p class="lead">نبض ساردو رسانه‌ای محلی برای پوشش دقیق، سریع و مسئولانه اخبار ساردوئیه و جنوب کرمان است.</p><div class="grid info"><div class="panel"><h3>ماموریت</h3><p>خبر محلی قابل اتکا و روایت مسائل واقعی مردم.</p></div><div class="panel"><h3>اصول تحریریه</h3><p>دقت، راستی‌آزمایی، احترام و استقلال.</p></div><div class="panel"><h3>تمرکز منطقه‌ای</h3><p>ساردوئیه، جیرفت و جنوب کرمان.</p></div></div>`;}else if(type==='contact'){title='تماس با ما';content=`${ok?'<div class="success">پیام شما ثبت شد.</div>':''}<form class="form" method="post"><label>نام<input name="name" required></label><label>راه ارتباطی<input name="contact" required></label><label>موضوع<input name="subject" required></label><label>پیام<textarea name="message" required></textarea></label><button class="btn primary">ارسال پیام</button></form>`;}else{title='ارسال خبر مردمی';content=`<div class="send-news-gift-box gift-card-box"><span>هدیه خبر مردمی</span><b>در صورت تمایل، شماره کارت خود را وارد کنید تا اگر خبر شما مشمول هدیه شد، مبلغ برایتان واریز شود.</b></div>${ok?'<div class="success">خبر شما همراه فایل برای تحریریه ثبت شد.</div>':''}${uploadError==='large'?'<div class="error">حجم فایل بیشتر از ۵۰ مگابایت است.</div>':uploadError==='type'?'<div class="error">فرمت فایل پشتیبانی نمی‌شود. عکس یا ویدئوی MP4/WebM/MOV انتخاب کنید.</div>':''}<form class="form citizen-form" method="post" enctype="multipart/form-data"><label>نام<input name="name" required></label><label>شماره تماس<input name="phone" required></label><label>محل رویداد<input name="location" required></label><label>عنوان خبر<input name="headline" required></label><label>شرح خبر<textarea name="details" required></textarea></label><label class="citizen-upload">عکس یا ویدئوی خبر<input type="file" name="mediaFile" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" required><small>فایل را مستقیم از گوشی انتخاب و آپلود کنید؛ حداکثر حجم ۵۰ مگابایت.</small></label><label class="reward-card-input">شماره کارت برای دریافت هدیه <small>اختیاری — فقط برای واریز هدیه احتمالی استفاده می‌شود.</small><input name="rewardCard" inputmode="numeric" autocomplete="off" maxlength="24" placeholder="مثلاً 6037 99xx xxxx xxxx"></label><button class="btn primary">ارسال برای تحریریه</button></form>`;}const canonical=type==='about'?'/about':type==='contact'?'/contact':'/send-news';return shell(title+' | نبض ساردو',`${header(db)}<main class="wrap page"><span class="eyebrow">NABEZ SARDO</span><h1>${title}</h1>${content}</main>${footer()}`,title+' | نبض ساردو',{canonical});}
module.exports={home,archive,article,category,simple,search};