const PUBLIC_BASE=(process.env.PUBLIC_BASE_URL||'https://nabzesardo.ir').replace(/\/+$/,'');
function absoluteUrl(v=''){const s=String(v||'');if(/^https?:\/\//i.test(s))return s;return PUBLIC_BASE+(s.startsWith('/')?s:'/'+s);}
function schemaScript(data){if(!data)return '';const list=Array.isArray(data)?data:[data];return list.filter(Boolean).map(x=>'<script type="application/ld+json">'+JSON.stringify(x).replace(/</g,'\\u003c')+'</script>').join('');}
function e(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const CATEGORY_EN={'سیاسی':'Politics','ساردوئیه':'Sardouiyeh','اجتماعی':'Society','فرهنگ':'Culture','فرهنگ و ورزش':'Culture & Sports','ورزش':'Sports','کشاورزی':'Agriculture','گردشگری':'Tourism','اقتصادی':'Economy','حوادث':'Incidents','آموزش':'Education'};
function catEn(name=''){return CATEGORY_EN[String(name)]||String(name||'News');}
function bi(fa,en=''){return '<span class="lang-fa">'+e(fa)+'</span><span class="lang-en">'+e(en||fa)+'</span>';}
function fmt(iso){try{return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tehran'}).format(new Date(iso));}catch{return iso||'';}}
function shell(title,body,desc='نبض ساردو؛ رسانه محلی ساردوئیه و جنوب کرمان',opts={}){
const canonical=opts.canonical?absoluteUrl(opts.canonical):'';
const image=opts.image?absoluteUrl(opts.image):'';
const robots=opts.robots||'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1';
const ogType=opts.ogType||'website';
const preloadImage=opts.preloadImage?absoluteUrl(opts.preloadImage):'';
const preconnect=opts.preconnect||'';
const editorAssets=opts.editorAssets===true||body.includes('class="wrap admin"')||body.includes('class="login"');
const verify=process.env.GOOGLE_SITE_VERIFICATION?'<meta name="google-site-verification" content="'+e(process.env.GOOGLE_SITE_VERIFICATION)+'">':'';
return `<!doctype html><html lang="fa-IR" dir="rtl" data-lang="fa"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(desc)}"><meta name="robots" content="${e(robots)}"><meta name="googlebot" content="${e(robots)}">${verify}${preconnect?'<link rel="preconnect" href="'+e(preconnect)+'">':''}${preloadImage?'<link rel="preload" as="image" href="'+e(preloadImage)+'" fetchpriority="high">':''}${canonical?'<link rel="canonical" href="'+e(canonical)+'">':''}<link rel="sitemap" type="application/xml" href="${e(absoluteUrl('/sitemap.xml'))}"><link rel="alternate" type="application/rss+xml" title="نبض ساردو" href="${e(absoluteUrl('/feed.xml'))}"><meta name="theme-color" content="#090b0f"><meta property="og:locale" content="fa_IR"><meta property="og:site_name" content="نبض ساردو"><meta property="og:type" content="${e(ogType)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(desc)}"><meta property="og:url" content="${e(canonical)}">${image?'<meta property="og:image" content="'+e(image)+'"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="'+e(image)+'">':'<meta name="twitter:card" content="summary">'}<meta name="twitter:title" content="${e(title)}"><meta name="twitter:description" content="${e(desc)}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&family=Vazirmatn:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/site.css?v=homepage-newsdesk-v1"><link rel="stylesheet" href="/assets/header-fix.css?v=hero-motion-strong-v4"><link rel="stylesheet" href="/assets/editor.css?v=rich-editor-fonts-v1">${schemaScript(opts.schema)}</head><body>${body}<script src="/assets/site.js?v=perf-mobile-v1" defer></script>${editorAssets?'<script src="/assets/editor.js?v=rich-editor-fonts-v1" defer></script>':''}</body></html>`;}
function logo(){return `<a class="brand" href="/"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 64 64" role="img"><defs><linearGradient id="brandPulseGold" x1="5" y1="17" x2="59" y2="46" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#9b6a2b"/><stop offset=".28" stop-color="#f0ce84"/><stop offset=".58" stop-color="#fff1bc"/><stop offset="1" stop-color="#9a6a2d"/></linearGradient></defs><path d="M5 34h13l5-8 6 18 7-27 8 22 6-7h9" fill="none" stroke="#6e491e" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" opacity=".48"/><path d="M5 34h13l5-8 6 18 7-27 8 22 6-7h9" fill="none" stroke="url(#brandPulseGold)" stroke-width="3.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M5 32.7h13l5-8 6 18 7-27 8 22 6-7h9" fill="none" stroke="#fff3c8" stroke-width=".9" stroke-linecap="round" stroke-linejoin="round" opacity=".7"/></svg></span><b><span class="lang-fa">نبض ساردو</span><span class="lang-en">Nabez Sardo</span><small>NABEZ SARDO · NEWSROOM</small></b></a>`;}
function header(db){return `<div class="top"><div class="wrap row top-row"><div class="top-copy"><span class="lang-fa">نبض ساردو · رسانه محلی ساردوئیه و جنوب کرمان</span><span class="lang-en">Nabez Sardo · Local media of Sardouiyeh and South Kerman</span></div><div class="top-tools"><div class="lang-switcher" aria-label="Language"><button type="button" data-lang-option="fa" class="lang-btn active">FA</button><button type="button" data-lang-option="en" class="lang-btn">EN</button></div></div></div></div><header><div class="wrap row main">${logo()}<form class="header-search" action="/search" method="get" role="search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.8"></circle><path d="m16 16 4 4"></path></svg><input name="q" type="search" placeholder="جستجو در خبرها..." data-placeholder-fa="جستجو در خبرها..." data-placeholder-en="Search news..." aria-label="جستجو در خبرها"><button type="submit"><span class="lang-fa">جستجو</span><span class="lang-en">Search</span></button></form><div class="actions"><div class="theme-switcher" aria-label="تغییر رنگ قالب"><button type="button" class="theme-dot theme-gold" data-theme-option="gold" aria-label="طلایی" title="طلایی"></button><button type="button" class="theme-dot theme-blue" data-theme-option="blue" aria-label="آبی" title="آبی"></button><button type="button" class="theme-dot theme-green" data-theme-option="green" aria-label="سبز" title="سبز"></button><button type="button" class="theme-dot theme-burgundy" data-theme-option="burgundy" aria-label="زرشکی" title="زرشکی"></button></div><a class="btn ghost" href="/all-news"><span class="lang-fa">آرشیو</span><span class="lang-en">Archive</span></a><a class="btn primary" href="/send-news"><span class="lang-fa">ارسال خبر مردمی</span><span class="lang-en">Send a Story</span></a></div></div></header><nav><div class="wrap navrow"><a href="/"><span class="lang-fa">صفحه اصلی</span><span class="lang-en">Home</span></a><a href="/all-news"><span class="lang-fa">آخرین اخبار</span><span class="lang-en">Latest News</span></a>${db.categories.slice(0,7).map(c=>`<a href="/category/${encodeURIComponent(c.id)}"><span class="lang-fa">${e(c.name)}</span><span class="lang-en">${e(catEn(c.name))}</span></a>`).join('')}<a href="/contact"><span class="lang-fa">تماس</span><span class="lang-en">Contact</span></a></div></nav>`;}
function footer(){return `<footer><div class="wrap foot"><div><h3><span class="lang-fa">نبض ساردو</span><span class="lang-en">Nabez Sardo</span></h3><p><span class="lang-fa">خبر دقیق، روایت انسانی و هویت منطقه.</span><span class="lang-en">Accurate news, human stories, local identity.</span></p></div><div><h4><span class="lang-fa">رسانه</span><span class="lang-en">Media</span></h4><a href="/about"><span class="lang-fa">درباره ما</span><span class="lang-en">About</span></a><a href="/contact"><span class="lang-fa">تماس</span><span class="lang-en">Contact</span></a><a href="/send-news"><span class="lang-fa">ارسال خبر</span><span class="lang-en">Send a Story</span></a></div><div><h4><span class="lang-fa">دسترسی</span><span class="lang-en">Quick Links</span></h4><a href="/"><span class="lang-fa">خانه</span><span class="lang-en">Home</span></a><a href="/all-news"><span class="lang-fa">آرشیو</span><span class="lang-en">Archive</span></a></div><div><h4>NABEZ SARDO</h4><p>Independent Local Newsroom</p></div></div><div class="copy"><span class="lang-fa">© نبض ساردو — تمامی حقوق محفوظ است.</span><span class="lang-en">© Nabez Sardo — All rights reserved.</span></div></footer>`;}
function imageRatio(a){const r=Number(a?.imageRatio);return Number.isFinite(r)&&r>0?r:16/9;}
function imageOrientation(a){const o=String(a?.imageOrientation||'');if(['portrait','square','landscape'].includes(o))return o;const r=imageRatio(a);return r<.92?'portrait':r>1.08?'landscape':'square';}
function card(a,db){
  const c=db.categories.find(x=>x.id===a.categoryId),ratio=imageRatio(a),orient=imageOrientation(a);
  const titleEn=a.titleEn||a.title,leadEn=a.leadEn||a.lead,image=a.image||'/assets/placeholder.svg';
  const url='/news/'+encodeURIComponent(a.slug),catFa=c?.name||'خبر',catEnglish=catEn(c?.name||'News');
  const rawBodyFa=String(a.body||a.bodyHtml||a.lead||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
  const rawBodyEn=String(a.bodyEn||a.bodyHtmlEn||a.leadEn||rawBodyFa).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
  const storyBodyFa=rawBodyFa.length>280?rawBodyFa.slice(0,277).trim()+'…':rawBodyFa;
  const storyBodyEn=rawBodyEn.length>280?rawBodyEn.slice(0,277).trim()+'…':rawBodyEn;
  return `<article class="card tilt" data-story-card data-story-title-fa="${e(a.title)}" data-story-title-en="${e(titleEn)}" data-story-lead-fa="${e(a.lead||'')}" data-story-lead-en="${e(leadEn||'')}" data-story-body-fa="${e(storyBodyFa)}" data-story-body-en="${e(storyBodyEn)}" data-story-image="${e(image)}" data-story-category-fa="${e(catFa)}" data-story-category-en="${e(catEnglish)}" data-story-url="${e(url)}"><a class="card-media ${orient}" data-adaptive-media style="--image-ratio:${ratio}" href="${url}"><img src="${e(image)}" alt="${e(a.title)}" loading="lazy" decoding="async" fetchpriority="low"><span class="card-story-badge"><span class="card-story-dot" aria-hidden="true"></span><span class="lang-fa">استوری</span><span class="lang-en">Story</span></span></a><div class="pad"><div class="card-kicker"><span class="eyebrow"><span class="lang-fa">${e(catFa)}</span><span class="lang-en">${e(catEnglish)}</span></span><span class="view-badge">◉ ${Number(a.views||0).toLocaleString('fa-IR')}</span></div><time class="news-date" data-news-date="${e(a.publishedAt||a.createdAt||'')}"></time><h3><a href="${url}"><span class="lang-fa">${e(a.title)}</span><span class="lang-en">${e(titleEn)}</span></a></h3><p><span class="lang-fa">${e(a.lead||'')}</span><span class="lang-en">${e(leadEn||'')}</span></p><a class="more" href="${url}"><span class="lang-fa">مطالعه خبر ←</span><span class="lang-en">Read story →</span></a></div></article>`;
}

function oldBody(a){return e(a.body||'').split('\n').filter(Boolean).map(p=>`<p>${p}</p>`).join('');}
module.exports={e,fmt,shell,logo,header,footer,card,oldBody,imageRatio,imageOrientation,absoluteUrl,PUBLIC_BASE,bi,catEn};